In [63]:
%pip install pyodbc pandas

Requirement already satisfied: pyodbc in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.3.0)
Requirement already satisfied: pandas in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\tablo\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Base de datos permiso de circulación 2022

In [64]:
import pyodbc

# Lista los drivers instalados en tu sistema
for driver in pyodbc.drivers():
    if "Access" in driver:
        print(driver)

Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Access Text Driver (*.txt, *.csv)
Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)

In [65]:
import pyodbc

ruta_bd = r".\base-de-datos-permisos-de-circulación 2022.accdb"
conn_str = r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + ruta_bd

conexion = pyodbc.connect(conn_str)
cursor = conexion.cursor()

# Obtener los nombres de todas las tablas
tablas = [row.table_name for row in cursor.tables(tableType="TABLE")]
print("Tablas encontradas en la base de datos:")
for t in tablas:
    print(f"- {t}")

conexion.close()

Tablas encontradas en la base de datos:
- TBL_VehículosConMotor
- TBL_VehículosSinMotor

In [66]:
import pandas as pd
import pyodbc

ruta_bd = r".\base-de-datos-permisos-de-circulación 2022.accdb"

conn_str = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    f"DBQ={ruta_bd};"
)

conexion = pyodbc.connect(conn_str)
nombre_tabla_real = "TBL_VehículosConMotor"

query = f"SELECT * FROM [{nombre_tabla_real}]"
df2022 = pd.read_sql(query, conexion)

conexion.close()
print("los primeros 5 registros")
df2022.head()

C:\Users\tablo\AppData\Local\Temp\ipykernel_22956\2594171917.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2022 = pd.read_sql(query, conexion)

los primeros 5 registros

,Año,Glosa Región,Glosa Comuna,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
0,2022.0,Región de Tarapacá,Iquique,1.0,1.0,48464.0,20462.0,51.0,17.0,0.0,68499.0,495.0
1,2022.0,Región de Tarapacá,Iquique,1.0,2.0,170.0,912.0,0.0,0.0,0.0,1077.0,5.0
2,2022.0,Región de Tarapacá,Iquique,1.0,6.0,45.0,123.0,0.0,0.0,0.0,145.0,23.0
3,2022.0,Región de Tarapacá,Iquique,1.0,3.0,9.0,326.0,0.0,0.0,0.0,331.0,4.0
4,2022.0,Región de Tarapacá,Iquique,1.0,4.0,1657.0,6839.0,0.0,0.0,0.0,8455.0,41.0

In [67]:
print("Filas y columnas del dataset")
df2022.shape

Filas y columnas del dataset

(4748, 12)

In [68]:
df2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 4748 entries, 0 to 4747
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           4748 non-null   float64
 1   Glosa Región  4748 non-null   str
 2   Glosa Comuna  4748 non-null   str
 3   Destino       4748 non-null   float64
 4   TipoVehiculo  4748 non-null   float64
 5   Bencina       4748 non-null   float64
 6   Diésel        4748 non-null   float64
 7   Gas           4748 non-null   float64
 8   Eléctrico     4748 non-null   float64
 9   Otro          4748 non-null   float64
 10  Catalítico    4748 non-null   float64
 11  NoCatalítico  4748 non-null   float64
dtypes: float64(10), str(2)
memory usage: 609.8 KB

In [69]:
df2022.isnull().sum()

Año             0
Glosa Región    0
Glosa Comuna    0
Destino         0
TipoVehiculo    0
Bencina         0
Diésel          0
Gas             0
Eléctrico       0
Otro            0
Catalítico      0
NoCatalítico    0
dtype: int64

In [70]:
df2022.duplicated().sum()

np.int64(0)

In [71]:
df2022.describe()

,Año,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
count,4748.0,4748.000000,4748.000000,4748.000000,4748.000000,4748.000000,4748.000000,4748.0,4748.000000,4748.000000
mean,2022.0,1.853412,7.926706,941.902485,345.496209,1.181971,1.853201,0.0,1268.614996,21.818871
std,0.0,0.819241,4.422649,5147.723672,1055.231495,14.820283,16.547235,0.0,5673.505675,73.762939
min,2022.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,2022.0,1.000000,4.000000,0.000000,5.000000,0.000000,0.000000,0.0,20.000000,0.000000
50%,2022.0,2.000000,8.000000,6.000000,45.000000,0.000000,0.000000,0.0,83.000000,1.000000
75%,2022.0,3.000000,12.000000,109.250000,216.250000,0.000000,0.000000,0.0,396.000000,8.000000
max,2022.0,3.000000,15.000000,122652.000000,22938.000000,547.000000,446.000000,0.0,128352.000000,1164.000000

------------------------------------

## Base de datos permisos 2023

In [72]:
import pandas as pd
import pyodbc

ruta_bd = r".\base-de-datos-permisos-de-circulación 2023.accdb"

conn_str = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    f"DBQ={ruta_bd};"
)

conexion = pyodbc.connect(conn_str)
nombre_tabla_real = "TBL_VehículosConMotor"

query = f"SELECT * FROM [{nombre_tabla_real}]"
df2023 = pd.read_sql(query, conexion)

conexion.close()
print("los primeros 5 registros")
df2023.head()

los primeros 5 registros

C:\Users\tablo\AppData\Local\Temp\ipykernel_22956\226233836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2023 = pd.read_sql(query, conexion)

,Año,Glosa Región,Glosa Comuna,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
0,2023.0,Región de Tarapacá,Iquique,1.0,1.0,50221.0,21722.0,36.0,40.0,0.0,71552.0,467.0
1,2023.0,Región de Tarapacá,Iquique,1.0,2.0,183.0,968.0,0.0,0.0,0.0,1146.0,5.0
2,2023.0,Región de Tarapacá,Iquique,1.0,6.0,53.0,140.0,0.0,0.0,0.0,170.0,23.0
3,2023.0,Región de Tarapacá,Iquique,1.0,3.0,6.0,364.0,0.0,0.0,0.0,365.0,5.0
4,2023.0,Región de Tarapacá,Iquique,1.0,4.0,1768.0,7330.0,1.0,1.0,0.0,9058.0,42.0

In [73]:
print("filas y columnas del dataset")
df2023.shape

filas y columnas del dataset

(4787, 12)

In [74]:
df2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 4787 entries, 0 to 4786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           4787 non-null   float64
 1   Glosa Región  4787 non-null   str
 2   Glosa Comuna  4787 non-null   str
 3   Destino       4787 non-null   float64
 4   TipoVehiculo  4787 non-null   float64
 5   Bencina       4787 non-null   float64
 6   Diésel        4787 non-null   float64
 7   Gas           4787 non-null   float64
 8   Eléctrico     4787 non-null   float64
 9   Otro          4787 non-null   float64
 10  Catalítico    4787 non-null   float64
 11  NoCatalítico  4787 non-null   float64
dtypes: float64(10), str(2)
memory usage: 614.9 KB

In [75]:
df2023.isnull().sum()

Año             0
Glosa Región    0
Glosa Comuna    0
Destino         0
TipoVehiculo    0
Bencina         0
Diésel          0
Gas             0
Eléctrico       0
Otro            0
Catalítico      0
NoCatalítico    0
dtype: int64

In [76]:
df2023.duplicated().sum()

np.int64(0)

In [77]:
df2023.describe()

,Año,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
count,4787.0,4787.000000,4787.000000,4787.000000,4787.000000,4787.000000,4787.000000,4787.0,4787.000000,4787.000000
mean,2023.0,1.856904,7.947357,969.028828,365.035931,1.350115,3.508878,0.0,1319.233549,19.690203
std,0.0,0.820111,4.421643,5288.253223,1134.204925,20.819520,29.870435,0.0,5870.396439,66.167984
min,2023.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,2023.0,1.000000,4.000000,0.000000,6.000000,0.000000,0.000000,0.0,21.000000,0.000000
50%,2023.0,2.000000,8.000000,6.000000,47.000000,0.000000,0.000000,0.0,87.000000,1.000000
75%,2023.0,3.000000,12.000000,112.000000,223.000000,0.000000,0.000000,0.0,403.000000,7.500000
max,2023.0,3.000000,15.000000,120778.000000,23395.000000,1094.000000,1143.000000,0.0,126573.000000,1228.000000

-----------------------------------------------------------

## Base de datos permisos 2024

In [78]:
import pandas as pd
import pyodbc

ruta_bd = r".\base-de-datos-permisos-de-circulación 2024.accdb"
conn_str = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    f"DBQ={ruta_bd};"
)

conexion = pyodbc.connect(conn_str)
nombre_tabla_real = "TBL_VehículosConMotor"

query = f"SELECT * FROM [{nombre_tabla_real}]"
df2024 = pd.read_sql(query, conexion)

conexion.close()
print("los primeros 5 registros")
df2024.head()

C:\Users\tablo\AppData\Local\Temp\ipykernel_22956\4061681606.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2024 = pd.read_sql(query, conexion)

los primeros 5 registros

,Año,Glosa Región,Glosa Comuna,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
0,2024.0,Región de Tarapacá,Iquique,1.0,1.0,51543.0,22122.0,31.0,227.0,0.0,73508.0,415.0
1,2024.0,Región de Tarapacá,Iquique,1.0,2.0,169.0,1144.0,0.0,0.0,0.0,1305.0,8.0
2,2024.0,Región de Tarapacá,Iquique,1.0,6.0,44.0,151.0,0.0,0.0,0.0,176.0,19.0
3,2024.0,Región de Tarapacá,Iquique,1.0,3.0,6.0,325.0,0.0,0.0,0.0,329.0,2.0
4,2024.0,Región de Tarapacá,Iquique,1.0,4.0,1922.0,7956.0,5.0,5.0,0.0,9839.0,49.0

In [79]:
print("filas y columnas del datasset")
df2024.shape

filas y columnas del datasset

(4777, 12)

In [80]:
df2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 4777 entries, 0 to 4776
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           4777 non-null   float64
 1   Glosa Región  4777 non-null   str
 2   Glosa Comuna  4777 non-null   str
 3   Destino       4777 non-null   float64
 4   TipoVehiculo  4777 non-null   float64
 5   Bencina       4777 non-null   float64
 6   Diésel        4777 non-null   float64
 7   Gas           4777 non-null   float64
 8   Eléctrico     4777 non-null   float64
 9   Otro          4777 non-null   float64
 10  Catalítico    4777 non-null   float64
 11  NoCatalítico  4777 non-null   float64
dtypes: float64(10), str(2)
memory usage: 613.5 KB

In [81]:
df2024.isnull().sum()

Año             0
Glosa Región    0
Glosa Comuna    0
Destino         0
TipoVehiculo    0
Bencina         0
Diésel          0
Gas             0
Eléctrico       0
Otro            0
Catalítico      0
NoCatalítico    0
dtype: int64

In [82]:
df2024.duplicated().sum()

np.int64(0)

In [83]:
df2024.describe()

,Año,Destino,TipoVehiculo,Bencina,Diésel,Gas,Eléctrico,Otro,Catalítico,NoCatalítico
count,4777.0,4777.000000,4777.000000,4777.000000,4777.000000,4777.000000,4777.000000,4777.0,4777.000000,4777.000000
mean,2024.0,1.854511,7.939920,992.139837,378.367804,2.520201,7.086665,0.0,1361.676785,18.437722
std,0.0,0.820830,4.423313,5410.805374,1200.120277,26.941738,84.308981,0.0,6047.434419,60.868711
min,2024.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,2024.0,1.000000,4.000000,0.000000,6.000000,0.000000,0.000000,0.0,22.000000,0.000000
50%,2024.0,2.000000,8.000000,6.000000,50.000000,0.000000,0.000000,0.0,91.000000,1.000000
75%,2024.0,3.000000,12.000000,115.000000,228.000000,0.000000,0.000000,0.0,417.000000,7.000000
max,2024.0,3.000000,15.000000,127517.000000,23467.000000,1183.000000,3999.000000,0.0,136611.000000,994.000000