In [34]:
import pandas as pd

df2024 = pd.read_csv("ruea-tr-2024-ckan_mejora.csv", sep=";")
df2023 = pd.read_csv("ruea-tr-2023-ckan.csv", sep=";")
df2022 = pd.read_csv("ruea-tr-2022-ckan.csv", sep=";")

In [ ]:
dfconcepcion24 = df2024[df2024['ciudad'] == 'Gran Concepción']

dfconcepcion24.head()

,id_comuna,año,cantidad_toneladas,id_contaminantes,contaminantes,tipo_vehiculo,tipo_emision,ciudad,tipo_vehiculo(ccf8)
1753,,2024,"3607,526375",73,Monóxido de carbono,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,Vehículos livianos de pasajeros gasolineros Eu...
1754,,2024,"340,703413",73,Monóxido de carbono,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,Vehículos livianos de pasajeros gasolineros Eu...
1755,,2024,"116,8281922",73,Monóxido de carbono,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,Vehículos livianos de pasajeros gasolineros si...
1756,,2024,"80,17674555",73,Monóxido de carbono,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,Vehículos livianos de pasajeros diesel Euro 1
1757,,2024,"322,6874597",73,Monóxido de carbono,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,Vehículos livianos de pasajeros gasolineros Eu...

In [35]:
print(f"Las dimensiones son del csv son: {df2024.shape}\n")

Las dimensiones son del csv son: (47817, 9)

In [36]:
df2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 47817 entries, 0 to 47816
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_comuna            47817 non-null  str
 1   año                  47817 non-null  int64
 2   cantidad_toneladas   47817 non-null  str
 3   id_contaminantes     47817 non-null  int64
 4   contaminantes        47817 non-null  str
 5   tipo_vehiculo        47817 non-null  str
 6   tipo_emision         47817 non-null  str
 7   ciudad               47817 non-null  str
 8   tipo_vehiculo(ccf8)  47817 non-null  str
dtypes: int64(2), str(7)
memory usage: 3.3 MB

In [37]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2024.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
id_comuna                str
año                    int64
cantidad_toneladas       str
id_contaminantes       int64
contaminantes            str
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
tipo_vehiculo(ccf8)      str
dtype: object

In [51]:
dfconcepcion24['id_comuna'].unique()

<StringArray>
[' ']
Length: 1, dtype: str

In [53]:
dfconcepcion23 = df2023[df2023['ciudad'] == 'Gran Concepción']

dfconcepcion23.head()

,contaminantes,id_contaminantes,tipo_vehiculo,tipo_emision,ciudad,cantidad_toneladas,año,region,provincia,comuna,id_comuna,tipo_vehiculo(ccf8)
285702,Nitrógeno amoniacal (o NH3),77,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,"4,955,583,909",2023,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285703,Mercurio,67,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,4.96E-03,2023,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285704,Metano (CH4),69,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,"1,840,645,452",2023,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285705,Monóxido de carbono,73,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,"1,111,568,609",2023,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285706,Dióxido de azufre (SO2),44,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,"0,194751228",2023,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...

In [55]:
dfconcepcion23['año'].unique()

array([2023])

In [38]:
print(f"Las dimensiones son del csv son: {df2023.shape}\n")

Las dimensiones son del csv son: (390560, 12)

In [39]:
df2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 390560 entries, 0 to 390559
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   contaminantes        390560 non-null  str
 1   id_contaminantes     390560 non-null  int64
 2   tipo_vehiculo        390560 non-null  str
 3   tipo_emision         390560 non-null  str
 4   ciudad               390560 non-null  str
 5   cantidad_toneladas   390560 non-null  str
 6   año                  390560 non-null  int64
 7   region               390560 non-null  str
 8   provincia            390560 non-null  str
 9   comuna               390560 non-null  str
 10  id_comuna            390560 non-null  int64
 11  tipo_vehiculo(ccf8)  390560 non-null  str
dtypes: int64(3), str(9)
memory usage: 35.8 MB

In [40]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2023.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
contaminantes            str
id_contaminantes       int64
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
cantidad_toneladas       str
año                    int64
region                   str
provincia                str
comuna                   str
id_comuna              int64
tipo_vehiculo(ccf8)      str
dtype: object

In [56]:
dfconcepcion22 = df2022[df2022['ciudad'] == 'Gran Concepción']

dfconcepcion22.head()

,contaminantes,id_contaminantes,tipo_vehiculo,tipo_emision,ciudad,cantidad_toneladas,año,region,provincia,comuna,id_comuna,tipo_vehiculo(ccf8)
285672,Nitrógeno amoniacal (o NH3),77,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,7089033987.00000000000,2022,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285673,Mercurio,67,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,0.00708903000,2022,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285674,Metano (CH4),69,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,2633069766.00000000000,2022,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285675,Monóxido de carbono,73,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,1342525887.00000000000,2022,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...
285676,Dióxido de azufre (SO2),44,Vehículos particulares,Tubo de Escape Vehiculos,Gran Concepción,"0,247406783",2022,Biobío,Concepción,Concepción,8101,Vehículos livianos de pasajeros gasolineros Eu...

In [57]:
dfconcepcion22['id_comuna'].unique()

array([8101, 8102, 8103, 8105, 8106, 8107, 8108, 8110, 8111, 8112])

In [41]:
print(f"Las dimensiones son del csv son: {df2022.shape}\n")

Las dimensiones son del csv son: (377591, 12)

In [42]:
df2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 377591 entries, 0 to 377590
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   contaminantes        377591 non-null  str
 1   id_contaminantes     377591 non-null  int64
 2   tipo_vehiculo        377591 non-null  str
 3   tipo_emision         377591 non-null  str
 4   ciudad               377591 non-null  str
 5   cantidad_toneladas   377591 non-null  str
 6   año                  377591 non-null  int64
 7   region               377591 non-null  str
 8   provincia            377591 non-null  str
 9   comuna               377591 non-null  str
 10  id_comuna            377591 non-null  int64
 11  tipo_vehiculo(ccf8)  377591 non-null  str
dtypes: int64(3), str(9)
memory usage: 34.6 MB

In [43]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2022.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
contaminantes            str
id_contaminantes       int64
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
cantidad_toneladas       str
año                    int64
region                   str
provincia                str
comuna                   str
id_comuna              int64
tipo_vehiculo(ccf8)      str
dtype: object