In [30]:
import pandas as pd

df2024 = pd.read_csv("ruea-tr-2024-ckan_mejora.csv", sep=";")
df2023 = pd.read_csv("ruea-tr-2023-ckan.csv", sep=";")
df2022 = pd.read_csv("ruea-tr-2022-ckan.csv", sep=";")

In [31]:
print(f"Las dimensiones son del csv son: {df2024.shape}\n")

Las dimensiones son del csv son: (47817, 9)

In [32]:
df2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 47817 entries, 0 to 47816
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_comuna            47817 non-null  str
 1   año                  47817 non-null  int64
 2   cantidad_toneladas   47817 non-null  str
 3   id_contaminantes     47817 non-null  int64
 4   contaminantes        47817 non-null  str
 5   tipo_vehiculo        47817 non-null  str
 6   tipo_emision         47817 non-null  str
 7   ciudad               47817 non-null  str
 8   tipo_vehiculo(ccf8)  47817 non-null  str
dtypes: int64(2), str(7)
memory usage: 3.3 MB

In [33]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2024.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
id_comuna                str
año                    int64
cantidad_toneladas       str
id_contaminantes       int64
contaminantes            str
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
tipo_vehiculo(ccf8)      str
dtype: object

In [34]:
df2024.describe()

           año  id_contaminantes
count  47817.0      47817.000000
mean    2024.0         85.972165
std        0.0         27.071184
min     2024.0         44.000000
25%     2024.0         69.000000
50%     2024.0         74.000000
75%     2024.0        122.000000
max     2024.0        132.000000

In [35]:
df2024.isnull().sum()

id_comuna              0
año                    0
cantidad_toneladas     0
id_contaminantes       0
contaminantes          0
tipo_vehiculo          0
tipo_emision           0
ciudad                 0
tipo_vehiculo(ccf8)    0
dtype: int64

In [51]:
(df2024['id_comuna'] == " ").sum()

np.int64(10094)

In [37]:
df2024.duplicated().sum()

np.int64(0)

In [38]:
print(f"Las dimensiones son del csv son: {df2023.shape}\n")

Las dimensiones son del csv son: (390560, 12)

In [39]:
df2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 390560 entries, 0 to 390559
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   contaminantes        390560 non-null  str
 1   id_contaminantes     390560 non-null  int64
 2   tipo_vehiculo        390560 non-null  str
 3   tipo_emision         390560 non-null  str
 4   ciudad               390560 non-null  str
 5   cantidad_toneladas   390560 non-null  str
 6   año                  390560 non-null  int64
 7   region               390560 non-null  str
 8   provincia            390560 non-null  str
 9   comuna               390560 non-null  str
 10  id_comuna            390560 non-null  int64
 11  tipo_vehiculo(ccf8)  390560 non-null  str
dtypes: int64(3), str(9)
memory usage: 35.8 MB

In [40]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2023.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
contaminantes            str
id_contaminantes       int64
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
cantidad_toneladas       str
año                    int64
region                   str
provincia                str
comuna                   str
id_comuna              int64
tipo_vehiculo(ccf8)      str
dtype: object

In [41]:
df2023.isnull().sum()

contaminantes          0
id_contaminantes       0
tipo_vehiculo          0
tipo_emision           0
ciudad                 0
cantidad_toneladas     0
año                    0
region                 0
provincia              0
comuna                 0
id_comuna              0
tipo_vehiculo(ccf8)    0
dtype: int64

In [42]:
df2023.describe()

       id_contaminantes       año      id_comuna
count     390560.000000  390560.0  390560.000000
mean          83.746999    2023.0   10507.289763
std           29.037799       0.0    3691.221953
min           35.000000    2023.0    1101.000000
25%           73.000000    2023.0    8101.000000
50%           77.000000    2023.0   13107.000000
75%          122.000000    2023.0   13128.000000
max          132.000000    2023.0   16103.000000

In [43]:
df2023.duplicated().sum()

np.int64(0)

In [44]:
print(f"Las dimensiones son del csv son: {df2022.shape}\n")

Las dimensiones son del csv son: (377591, 12)

In [45]:
df2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 377591 entries, 0 to 377590
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   contaminantes        377591 non-null  str
 1   id_contaminantes     377591 non-null  int64
 2   tipo_vehiculo        377591 non-null  str
 3   tipo_emision         377591 non-null  str
 4   ciudad               377591 non-null  str
 5   cantidad_toneladas   377591 non-null  str
 6   año                  377591 non-null  int64
 7   region               377591 non-null  str
 8   provincia            377591 non-null  str
 9   comuna               377591 non-null  str
 10  id_comuna            377591 non-null  int64
 11  tipo_vehiculo(ccf8)  377591 non-null  str
dtypes: int64(3), str(9)
memory usage: 34.6 MB

In [46]:
print(f"Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:\n{df2022.dtypes}")

Los diferentes tipos de columnas y el tipo de dato que contiene el csv son:
contaminantes            str
id_contaminantes       int64
tipo_vehiculo            str
tipo_emision             str
ciudad                   str
cantidad_toneladas       str
año                    int64
region                   str
provincia                str
comuna                   str
id_comuna              int64
tipo_vehiculo(ccf8)      str
dtype: object

In [47]:
df2022.isnull().sum()

contaminantes          0
id_contaminantes       0
tipo_vehiculo          0
tipo_emision           0
ciudad                 0
cantidad_toneladas     0
año                    0
region                 0
provincia              0
comuna                 0
id_comuna              0
tipo_vehiculo(ccf8)    0
dtype: int64

In [48]:
df2022.describe()

       id_contaminantes       año      id_comuna
count     377591.000000  377591.0  377591.000000
mean          83.743863    2022.0   10724.135077
std           29.058156       0.0    3681.651719
min           35.000000    2022.0    1101.000000
25%           73.000000    2022.0    8103.000000
50%           77.000000    2022.0   13109.000000
75%          122.000000    2022.0   13129.000000
max          132.000000    2022.0   16103.000000

In [49]:
df2022.duplicated().sum()

np.int64(0)